%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\ccm21008\Documents\GitHub\gbl_matlab_tools\merge_samples_with_btl\IEPAug2023\Final IEP logsheet N2O- Aug 2023.xlsx
%    Worksheet: SORTED BASED ON BOTTLE NUMBER
%
% Auto-generated by MATLAB on 06-Feb-2024 21:09:23

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = "SORTED BASED ON BOTTLE NUMBER";
opts.DataRange = "A2:C509";

% Specify column names and types
opts.VariableNames = ["Station", "Niskin", "SID"];
opts.VariableTypes = ["categorical", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Station", "EmptyFieldRule", "auto");

% Import the data
%IEP_SID = readtable("C:\Users\ccm21008\Documents\GitHub\gbl_matlab_tools\merge_samples_with_btl\IEPAug2023\Final IEP logsheet N2O- Aug 2023.xlsx", opts, "UseExcel", false);
IEP_SID = readtable("Final IEP logsheet N2O- Aug 2023.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

save IEP_SID.mat IEP_SID;