%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\ccm21008\GitHub\gbl_matlab_tools\merge_samples_with_btl\SKQ202309T\ctd\btl\skq202309t_001.btl
%
% Auto-generated by MATLAB on 06-Feb-2024 12:32:16

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 25);

% Specify range and delimiter
opts.DataLines = [3, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Bottle", "mmm", "dd", "yyyy", "DepSM", "Latitude", "Longitude", "PrDM", "T090C", "T190C", "Potemp090C", "Sal00", "Sal11", "Density00", "Sigma00", "Sbox0MmKg", "Sbox1MmKg", "OxsolMmKg", "Sbeox0PS", "V0", "FlECOAFL", "CStarAt0", "Scan", "Var24", "Var25"];
opts.SelectedVariableNames = ["Bottle", "mmm", "dd", "yyyy", "DepSM", "Latitude", "Longitude", "PrDM", "T090C", "T190C", "Potemp090C", "Sal00", "Sal11", "Density00", "Sigma00", "Sbox0MmKg", "Sbox1MmKg", "OxsolMmKg", "Sbeox0PS", "V0", "FlECOAFL", "CStarAt0", "Scan"];
opts.VariableTypes = ["double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var24", "Var25"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["mmm", "Var24", "Var25"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["Bottle", "dd"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["Bottle", "dd"], "ThousandsSeparator", ",");

% Import the data
skq202309t006 = readtable("C:\Users\ccm21008\GitHub\gbl_matlab_tools\merge_samples_with_btl\SKQ202309T\ctd\btl\skq202309t_006.btl", opts);


%% Clear temporary variables
clear opts


%% Remove the rows that are for the standard deviation

% remove the rows with a year that is not 2023
skq202309t006(skq202309t006.yyyy <2023, :) = [];

%% Save data
save skq202309t006.mat skq202309t006;