%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\ccm21008\OneDrive - University of Connecticut\research\Long Island Sound\Aug 2023 cruise\GC\SRI GC LIS Aug 2023 sorted.xlsx
%    Worksheet: Cells to Columns
%
% Auto-generated by MATLAB on 13-Feb-2024 14:57:31

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 19);

% Specify sheet and range
opts.Sheet = "Cells to columns new";
opts.DataRange = "A2:S254";

% Specify column names and types
opts.VariableNames = ["AnalysisDate", "SampleID", "Cruise", "SID", "Cast", "Station", "Niskin", "Note", "VarName9", "CH4nM", "CH4nmolkg", "N2OnM", "N2Onmolkg", "T", "S", "Density", "CH4PeakArea", "N2OPeakArea", "CO2PeakArea"];
opts.VariableTypes = ["datetime", "categorical", "categorical", "double", "categorical", "categorical", "categorical", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Note", "VarName9"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["SampleID", "Cruise", "Cast", "Station", "Niskin", "Note", "VarName9"], "EmptyFieldRule", "auto");

% Import the data
LISAug23GC = readtable("C:\Users\ccm21008\OneDrive - University of Connecticut\research\Long Island Sound\Aug 2023 cruise\GC\SRI GC LIS Aug 2023 sorted.xlsx", opts, "UseExcel", false);


save LISAug23GC.mat LISAug23GC;

%% Clear temporary variables
clear opts