%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\ccm21008\Documents\GitHub\gbl_matlab_tools\LIS\data\Bridgeport_May2024_CO-OPS_8467150_wl.csv
%
% Auto-generated by MATLAB on 10-Feb-2025 15:43:45

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Date", "TimeGMT", "Predictedft", "Preliminaryft", "Verifiedft"];
opts.VariableTypes = ["datetime", "datetime", "double", "categorical", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Preliminaryft", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Date", "InputFormat", "yyyy/MM/dd", "DatetimeFormat", "preserveinput");
opts = setvaropts(opts, "TimeGMT", "InputFormat", "HH:mm", "DatetimeFormat", "preserveinput");

% Import the data
%KingsPoint_Oct2023= readtable("C:\Users\ccm21008\Documents\GitHub\gbl_matlab_tools\LIS\data\KingsPoint_Oct2023_CO-OPS_8516945_wl.csv", opts);
KingsPoint_May2024= readtable("C:\Users\ccm21008\Documents\GitHub\gbl_matlab_tools\LIS\data\KingsPoint_May2024_CO-OPS_8516945_wl.csv", opts);
%KingsPoint_Aug2023= readtable("C:\Users\ccm21008\Documents\GitHub\gbl_matlab_tools\LIS\data\KingsPoint_Aug2023_CO-OPS_8516945_wl.csv", opts);
save KingsPoint_May2024.mat KingsPoint_May2024;
%%
%Bridgeport_Oct2023= readtable("C:\Users\ccm21008\Documents\GitHub\gbl_matlab_tools\LIS\data\Bridgeport_Oct2023_CO-OPS_8467150_wl.csv", opts);
Bridgeport_Aug2023= readtable("C:\Users\ccm21008\Documents\GitHub\gbl_matlab_tools\LIS\data\Bridgeport_Aug2023_CO-OPS_8467150_wl.csv", opts);

save Bridgeport_Aug2023.mat Bridgeport_Aug2023;

%% Clear temporary variables
clear opts