%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\OneDrive - University of Connecticut\research\Long Island Sound\Aug 2023 cruise\CTD_2023_08_01-03_TobiasKayCarsonCara\processed_20240210\filter\align\EXCR-cast01.cnv
%
% Auto-generated by MATLAB on 14-Nov-2024 16:26:36

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 25);

% Specify range and delimiter
opts.DataLines = [242, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["P_dbar", "S_1", "S_2", "T", "O2_umolkg", "O2_umolL", "O2_sat", "O2_sol", "PTemp", "Dens", "PDen", "time_s", "scan", "lat", "lon", "chl_fluor", "O2_umolkg2", "O2_umolL2", "pH", "D_m", "O2_V", "bpos", "nbf", "flag", "Var25"];
opts.SelectedVariableNames = ["P_dbar", "S_1", "S_2", "T", "O2_umolkg", "O2_umolL", "O2_sat", "O2_sol", "PTemp", "Dens", "PDen", "time_s", "scan", "lat", "lon", "chl_fluor", "O2_umolkg2", "O2_umolL2", "pH", "D_m", "O2_V", "bpos", "nbf", "flag"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, "Var25", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var25", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["P_dbar", "S_1", "S_2", "T", "O2_umolkg", "O2_umolL", "O2_sat", "O2_sol", "PTemp", "Dens"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["P_dbar", "S_1", "S_2", "T", "O2_umolkg", "O2_umolL", "O2_sat", "O2_sol", "PTemp", "Dens"], "ThousandsSeparator", ",");

% Import the data
MID4cast01 = readtable("D:\OneDrive - University of Connecticut\research\Long Island Sound\Aug 2023 cruise\CTD_2023_08_01-03_TobiasKayCarsonCara\processed_20240210\filter\align\MID4-cast01.cnv", opts);


%% Clear temporary variables
clear opts

%%
F=MID4cast01;
figure(2)
clf; 

subplot(1,3,1)
hold on;
plot(F.S_1,F.D_m);
plot(E.S,E.D_m);
axis ij;
xlim([26.2 26.9]);
xlim([26.2 27.0]);
xlabel('salinity');
ylabel('depth (m)');
title('MID4-cast01')
legend('SBE9','SBE19');

subplot(1,3,2)
hold on;
plot(F.T,F.D_m);
plot(E.T,E.D_m2);
axis ij;
xlim([20.5 22.5]);
xlim([20 24]);
xlabel('temperature (^oC)')
ylabel('depth (m)')


subplot(1,3,3)
hold on;
plot(F.O2_umolL,F.D_m);
plot(E.O2_umolL,E.D_m2);
axis ij;
xlim([0 250]);
xlabel('O_2 (\mumol/L)')
ylabel('depth (m)')

 print -dpng -r300 MID4_cast01_SBE9vsSBE19.png;
