%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\OneDrive - University of Connecticut\research\Long Island Sound\Aug 2023 cruise\SBE19plus_01906254_2023_aug\processed_cnvFiles\SBE19plus_01906254_2023_08_02_exrx_hh10filtalignderive.cnv
%
% Auto-generated by MATLAB on 14-Nov-2024 15:43:13

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = [553, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["scan", "timeS", "P_dbar", "D_m", "T", "C", "O2_V", "pH", "turb", "D_m2", "S", "O2_mgL", "O2_sat", "flag"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["scan", "timeS", "P_dbar", "D_m", "T", "C", "O2_V", "pH", "turb", "D_m2", "S", "O2_mgL", "O2_sat", "flag"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["scan", "timeS", "P_dbar", "D_m", "T", "C", "O2_V", "pH", "turb", "D_m2", "S", "O2_mgL", "O2_sat", "flag"], "ThousandsSeparator", ",");

% Import the data
%exrxhh10filtalignderive = readtable("D:\OneDrive - University of Connecticut\research\Long Island Sound\Aug 2023 cruise\SBE19plus_01906254_2023_aug\processed_cnvFiles\SBE19plus_01906254_2023_08_02_exrx_hh10filtalignderive.cnv", opts);

exrxhh25filtalignderive = readtable("D:\OneDrive - University of Connecticut\research\Long Island Sound\Aug 2023 cruise\SBE19plus_01906254_2023_aug\processed_cnvFiles\SBE19plus_01906254_2023_08_03_exrx_hh25filtalignderive.cnv", opts);

mid4hh09filtalignderive = readtable("D:\OneDrive - University of Connecticut\research\Long Island Sound\Aug 2023 cruise\SBE19plus_01906254_2023_aug\processed_cnvFiles\SBE19plus_01906254_2023_08_02_mid4_hh09filtalignderive.cnv", opts);


%% Clear temporary variables
clear opts

%%
E=mid4hh09filtalignderive;
E.O2_umolL = E.O2_mgL .* 1/31.99880 .* 1000;
figure(1)
clf; 
subplot(2,2,1)
hold on;
plot(E.S,E.D_m);
axis ij;

subplot(2,2,2)
hold on;
plot(E.T,E.D_m2);
axis ij;


subplot(2,2,3)
hold on;
plot(E.O2_umolL,E.D_m2);
axis ij;
