%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\ccm21008\OneDrive - University of Connecticut\research\Long Island Sound\Aug 2023 cruise\CTD_2023_08_01-03_TobiasKayCarsonCara\EXCR-cast01.bl
%
% Auto-generated by MATLAB on 26-Feb-2024 11:08:59

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [3, Inf];
opts.Delimiter = [" ", ","];

% Specify column names and types
opts.VariableNames = ["FireSeq", "Niskin", "Month", "Day", "Year", "Time", "ScanStart", "ScanEnd"];
opts.VariableTypes = ["double", "double", "categorical", "double", "double", "datetime", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Specify variable properties
opts = setvaropts(opts, "Month", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Time", "InputFormat", "HH:mm:ss");
opts = setvaropts(opts, ["FireSeq", "Niskin", "Day", "Year", "ScanStart", "ScanEnd"], "ThousandsSeparator", ",");

% Import the data
%MID4cast07_fireseq = readtable("C:\Users\ccm21008\OneDrive - University of Connecticut\research\Long Island Sound\Aug 2023 cruise\CTD_2023_08_01-03_TobiasKayCarsonCara\MID4-cast07.bl", opts);
MID5cast01_fireseq = readtable("C:\Users\ccm21008\OneDrive - University of Connecticut\research\Long Island Sound\October 2023 cruise\CTD_2023_10_18-20_TobiasKayCarsonCara\mid501.bl", opts);
save MID5cast01_fireseq.mat MID5cast01_fireseq;
%% Clear temporary variables
clear opts

% list of casts
[EXCR-cast01
EXCR-cast02
EXR1-cast01
MID3-cast01
MID3-cast01
MID4-cast01
MID4-cast02
MID4-cast03
MID4-cast04
MID4-cast05
MID4-cast06
MID4-cast07
MID4-cast08
MID4-cast09
MID4-cast10
MID4-cast11
MID4-cast12
MID4-cast13
MID4-cast14
MID5-cast01
WLI6-cast01
WLI7-cast01
WLIS-cast01
WLIS-cast02
]


sn=['EXCR-cast01'
'EXCR-cast02'
'EXR1-cast01'
'MID3-cast01'
'MID4-cast01'
'MID4-cast02'
'MID4-cast03'
'MID4-cast04'
'MID4-cast05'
'MID4-cast06'
'MID4-cast07'
'MID4-cast08'
'MID4-cast09'
'MID4-cast10'
'MID4-cast11'
'MID4-cast12'
'MID4-cast13'
'MID4-cast14'
'MID5-cast01'
'WLI6-cast01'
'WLI7-cast01'
'WLIS-cast01'
'WLIS-cast02'
];

%%

sn=['EXCRcast01'
'EXCRcast02'
'EXR1cast01'
'MID3cast01'
'MID4cast01'
'MID4cast02'
'MID4cast03'
'MID4cast04'
'MID4cast05'
'MID4cast06'
'MID4cast07'
'MID4cast08'
'MID4cast09'
'MID4cast10'
'MID4cast11'
'MID4cast12'
'MID4cast13'
'MID4cast14'
'MID5cast01'
'WLI6cast01'
'WLI7cast01'
'WLIScast01'
'WLIScast02'
];

%for i = 1:numel(sn)
for i = 1
    fn_btl = strcat([sn(i,:)],'_btl.mat');
    fn_fs = strcat([sn(i,:)],'_fireseq.mat');
    f_btl=load(fn_btl);
    f_fs=load(fn_fs);

end;