%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: G:\Shared drives\Gas Biogeochemistry Lab\projects\CIRCA 2022 seed grant\deployment Aug 5\8\0-8S12071.DAT
%
% Auto-generated by MATLAB on 12-Aug-2022 15:47:36

%% Set up the Import Options and import the data
%fpath = "G:\Shared drives\Gas Biogeochemistry Lab\projects\CIRCA 2022 seed grant\test deployment August 1 to 3\0-7S12071.DAT";
%fpath= "G:\Shared drives\Gas Biogeochemistry Lab\projects\CIRCA 2022 seed grant\deployment Aug 5\8\0-8S12071.DAT";
%fpath= "H:\Shared drives\Gas Biogeochemistry Lab\projects\CIRCA 2022 seed grant\deployment Aug 12\10\0-10S12071.DAT";
%fpath= "G:\Shared drives\Gas Biogeochemistry Lab\projects\CIRCA 2022 seed grant\deployment Sep 12\S12071\14\0-14S12071.DAT";
fpath= "G:\Shared drives\Gas Biogeochemistry Lab\projects\CIRCA 2022 seed grant\deployment Sep 12\S12073\6\0-6S12073.DAT";


opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [21, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["sample_num", "sample_date", "temp", "depth", "sal", "cond", "sound_vel", "Var8"];
opts.SelectedVariableNames = ["sample_num", "sample_date", "temp", "depth", "sal", "cond", "sound_vel"];
opts.VariableTypes = ["double", "datetime", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Specify variable properties
opts = setvaropts(opts, "Var8", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var8", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "sample_date", "InputFormat", "dd/MM/yyyy HH:mm:SS");

% Import the data
S12073 = readtable(fpath, opts);

% save the data to a mat file
save S12073_Sep12_Nov22.mat S12073;

%% Clear temporary variables
clear opts

%% Plot the data

figure(1)
clf; 
subplot(3,1,1)
plot(S12073.sample_date,S12073.temp)
ylabel('Temperature [^oC]')

subplot(3,1,2)
plot(S12073.sample_date,S12073.sal)
ylabel('Salinity( [PSS]')

subplot(3,1,3)
plot(S12073.sample_date,S12073.depth)
ylabel('Depth [m]')


