%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: G:\Shared drives\Gas Biogeochemistry Lab\projects\CIRCA 2022 seed grant\test deployment August 1 to 3\20220801 part 2 miniTDGP.txt
%
% Auto-generated by MATLAB on 16-Aug-2022 13:17:24

% Set up the Import Options and import the data
%fpath = "G:\Shared drives\Gas Biogeochemistry Lab\projects\CIRCA 2022 seed grant\test deployment August 1 to 3\20220801 part 2 miniTDGP.txt";
%fpath = "H:\Shared drives\Gas Biogeochemistry Lab\projects\CIRCA 2022 seed grant\deployment Aug 5\miniTDGP 20220805 to 20220819.txt";
fpath = "G:\Shared drives\Gas Biogeochemistry Lab\projects\CIRCA 2022 seed grant\deployment Sep 12\miniTDGP 20220912 to 20221122.txt";

opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [3, Inf];
opts.Delimiter = [" ", ","];

% Specify column names and types
opts.VariableNames = ["Var1", "yyyy", "mm", "dd", "HH", "MM", "SS", "T", "P", "SupplyV", "Var11"];
opts.SelectedVariableNames = ["yyyy", "mm", "dd", "HH", "MM", "SS", "T", "P", "SupplyV"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var11"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var11"], "EmptyFieldRule", "auto");

% Import the data
miniTDGP = readtable(fpath, opts);


save miniTDGP.mat miniTDGP;

%% Clear temporary variables
clear opts