%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\ccm21008\GitHub\gbl_matlab_tools\MIMS\data\Membrane Test Data\20251111 1231 SEM 1600 35 eV 200 emission 7500 ion 180 anode 100 focus.csv
%
% Auto-generated by MATLAB on 19-Nov-2025 12:48:15

%% Set up the Import Options and import the data

% this is dependent on the columns matching the order below. if the
% formatting changes then this code will be wrong

%fn = '20251111 1231 SEM 1600 35 eV 200 emission 7500 ion 180 anode 100 focus.csv';
%file_path = 'data/Membrane Test Data/';
%mat_fn = '20251111_1231_mims.mat';

% fn = '20251113 1800 SEM varying 35 eV 400 emission 8000 ion 180 anode 100 focus.csv';
% file_path = 'data/Capillary Test Data/';
% mat_fn = '20251113_1800_mims.mat';

% fn = '20251114 1151 SEM varying 35 eV 400 emission 8000 ion 180 anode 100 focus.csv';
% file_path = 'data/Capillary Test Data/';
% mat_fn = '20251114_1151_mims.mat';

fn = '20251114 1310 SEM varying 35 eV 400 emission 8000 ion 180 anode 100 focus.csv';
file_path = 'data/Capillary Test Data/';
mat_fn = '20251114_1310_mims.mat';


opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = [54, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["idx", "dt", "m22", "m23", "m33p5", "m36", "m38", "m84", "m88", "tp", "r3836", "r2236", "r8436", "r2284"];
opts.VariableTypes = ["double", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "dt", "InputFormat", "MM/dd/yyyy hh:mm:ss aa", "DatetimeFormat", "preserveinput");
opts = setvaropts(opts, ["idx", "m22", "m23", "m33p5", "m36", "m38", "m84", "m88", "tp", "r3836", "r2236", "r8436", "r2284"], "ThousandsSeparator", ",");

% Import the data
mims = readtable([file_path fn], opts);
%mims = readtable("C:\Users\ccm21008\GitHub\gbl_matlab_tools\MIMS\data\Membrane Test Data\20251111 1231 SEM 1600 35 eV 200 emission 7500 ion 180 anode 100 focus.csv", opts);

% save data to mat file
fp = [file_path mat_fn];
save(fp, 'mims');

%% Clear temporary variables
clear opts